image: golangci/golangci-lint:latest

stages:
  - test

.go-mod:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

test:
  stage: test
  extends: .go-mod
  script:
    - make test

gofmt:
  stage: test
  script:
    - make gofmt

lint:
  stage: test
  extends: .go-mod
  script:
    - make lint
